In [ ]:
#In the name of God
#plan of action:
    #1-prepare the data:                                       done
        #load                                                      done                
        #trim                                                      done
        #partition (train, validation, test)                       done
    #2-write SGD on a train data & determined hyperparameters: done
        #yada
        #yada
    #3-set hyperparameters on validation data:
        #yada
        #yada
    #4-submit 
    

In [1]:
from sklearn import datasets
import numpy as np
data = datasets.load_diabetes()
X = data.data
Y = data.target

In [15]:
n, d = X.shape
trsize = int(0.7*n)
vasize = int(0.85*n)
Xt = X[0:trsize, :] ; Yt = Y[0:trsize]
Xv = X[trsize:vasize, :] ; Yv = Y[trsize:vasize]
Xte = X[vasize:n, :] ; Yte = Y[vasize:n]
print(Xt.shape)
print(Xv.shape)
print(Xte.shape)

(309, 10)
(66, 10)
(67, 10)


In [3]:
print(X[308,:] == Xt[308,:])
print(X[309,:] == Xv[0,:])
print(X[375,:] == Xte[0,:])

[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True  True  True]


$$
J(\tilde{W}) = ||Y-\tilde{D}\tilde{W}||^2 + \alpha ||\tilde{W}||^2
\\ SGD:
\\ \nabla_{\tilde{W}} = \frac{\partial}{\partial\tilde{W}}(J(\tilde{W}))=-\tilde{D^T}Y+(\tilde{D^T}\tilde{D})\tilde{W}+ \alpha \tilde{W}
$$

In [40]:
### SGD ###
def SGD(X,Y,eta=0.001,eps=1e-4,alpha=0.01):
    n,d = X.shape
    Dt = np.hstack((np.ones((n,1)),X))
    W0 = np.random.randn(d+1)
    epoch = 1
    while True:
        ii = np.arange(n)
        np.random.shuffle(ii)
        for i in ii:
            x,y = Dt[i],Y[i]
            Dw = -x*(y-x@W0) + alpha*W0
            W = W0 - eta*Dw
            chg = sum(abs(W/W0-1))
            if chg < eps: break
            W0 = W
        epoch += 1
        if epoch > 10000: break
    print(f"epoch {epoch} with W change: {chg:0.5f}")
    return W
    
W = SGD(Xt,Yt)
print(W.round(3))

epoch 10001 with W change: 0.00010
[150.496  25.903 -18.253 137.283  92.182  27.1    13.372 -80.402  77.989
 129.686  76.135]


In [41]:
no, d = Xt.shape

In [42]:
np.linalg.norm(Yt-np.hstack((np.ones((no,1)), Xt)) @ W)

1154.0137221781808

In [7]:
ii = np.arange(10)
np.random.shuffle(ii)
ii

array([8, 9, 0, 1, 2, 7, 6, 5, 4, 3])

In [18]:
ir = np.arange(10)
ir[0:4]

array([0, 1, 2, 3])

In [2]:
df

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [7]:
date = data.data
tar = data.target

In [10]:
date
tar

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28